classdef CSSuiTable < CSSBase
    %CSSUITABLE  CSS-styled data table backed by uihtml
    %
    %   Usage:
    %       t = CSSuiTable(parent, 'Data', myCell, 'ColumnName', {'Name','Fs','Files'})
    %       t = CSSuiTable(parent, 'Data', myCell, 'ColumnWidth', [200 80 80], 'Style', 'shadow')
    %       t.SelectionChangedFcn = @(s,e) disp(e.Selection);
    %       t.Data = newData;            % live update — no full reload
    %
    %   Inputs:
    %       parent : ui container - parent (default: new uifigure)
    %
    %   Name-Value Pairs:
    %       'Position'            : 1x4 double - [x y w h] (default: [10 10 400 250])
    %       'Enabled'             : logical - enable interaction (default: true)
    %       'TempDir'             : char - scratch dir (default: tempdir())
    %       'Style'               : char - CSSBase style preset (default: 'shadow')
    %       'CSS'                 : char - extra CSS (default: '')
    %       'CSSFile'             : char - extra CSS file (default: '')
    %       'Data'                : NxC cell - display values (default: {})
    %       'ColumnName'          : 1xC cell - header strings (default: {})
    %       'ColumnWidth'         : 1xC double - pixel widths, [] = auto (default: [])
    %       'SelectionType'       : char - 'row' | 'cell' | 'none' (default: 'row')
    %       'Selection'           : row indices or Nx2 [row col] pairs (default: [])
    %       'SelectionChangedFcn' : @(src, evt) on click (default: [])
    %       'DoubleClickFcn'      : @(src, evt) on double-click (default: [])
    %       'RowStriping'         : logical - alternate row shading (default: true)
    %       Additional CSS convenience properties are forwarded to CSSBase
    %       (Color, BackgroundColor, FontSize, Padding, BorderRadius, etc.).
    %
    %   Outputs:
    %       t : CSSuiTable handle
    %
    %   Notes:
    %       SelectionChangedFcn event struct has fields .Source, .Selection,
    %       .PreviousSelection. DoubleClickFcn event struct has .Source, .Row.
    %
    %       CSS element schema:
    %           #css-root                Outer sizing container (CSSBase-managed)
    %             .css-control           Scrollable table wrapper
    %               table                <table> element
    %                 thead > tr > th    Column headers
    %                 tbody > tr         Data rows
    %                   td               Data cells
    %               .tbl-row.selected    Highlighted selected row(s)
    %               .tbl-cell.selected   Highlighted selected cell (cell mode)
    %           .css-disabled            On #css-root when Enabled=false
    %
    %   Example:
    %       t.CSS = 'th { background: #dce4f0; }';
    %       t.CSS = '.tbl-row.selected td { background: #bbdefb; }';
    %       t.CSS = 'td { font-size: 11px; }';
    %
    %   See also: CSSBase, CSSuiListBox, CSSuiEditField
    %
    %   ∿∿∿  Prerau Laboratory MATLAB Codebase · sleepEEG.org  ∿∿∿
    %        Source: https://github.com/preraulab/labcode_main

    properties (Access = public)
        SelectionChangedFcn = []
        DoubleClickFcn      = []
        SelectionType       = 'row'   % 'row' | 'cell' | 'none'
        RowStriping         = true
    end

    properties (Dependent)
        Data
        ColumnName
        ColumnWidth
        Selection
    end

    properties (Access = protected)
        Data_        = {}
        ColumnName_  = {}
        ColumnWidth_ = []
        Selection_   = []     % row indices (row) or Nx2 (cell)
    end

    % =====================================================================
    methods
        function obj = CSSuiTable(parent, options)
            arguments
                parent = []
                options.Position        (1,4) double  = [10 10 400 250]
                options.Enabled         (1,1) logical = true
                options.TempDir         (1,:) char    = tempdir()
                options.Style                         = 'shadow'
                options.CSS             (1,:) char    = ''
                options.CSSFile         (1,:) char    = ''
                options.Data                          = {}
                options.ColumnName      (1,:) cell    = {}
                options.ColumnWidth                   = []
                options.SelectionType   (1,:) char    = 'row'
                options.Selection                     = []
                options.SelectionChangedFcn           = []
                options.DoubleClickFcn                = []
                options.RowStriping     (1,1) logical = true
                % --- CSS convenience properties (forwarded to CSSBase) ----
                options.Color               (1,:) char = ''
                options.BackgroundColor     (1,:) char = ''
                options.FontSize            (1,:) char = ''
                options.FontFamily          (1,:) char = ''
                options.FontWeight          (1,:) char = ''
                options.FontStyle           (1,:) char = ''
                options.LetterSpacing       (1,:) char = ''
                options.LineHeight          (1,:) char = ''
                options.TextTransform       (1,:) char = ''
                options.TextDecoration      (1,:) char = ''
                options.HorizontalAlignment (1,:) char = ''
                options.VerticalAlignment   (1,:) char = ''
                options.BorderRadius        (1,:) char = ''
                options.BoxShadow           (1,:) char = ''
                options.InsetShadow         (1,:) char = ''
                options.Opacity             (1,:) char = ''
                options.Cursor              (1,:) char = ''
                options.Padding             (1,:) char = ''
                options.MinWidth            (1,:) char = ''
                options.MinHeight           (1,:) char = ''
                options.MaxWidth            (1,:) char = ''
                options.MaxHeight           (1,:) char = ''
                options.Width               (1,:) char = ''
                options.Height              (1,:) char = ''
                options.OuterPadding        (1,:) char = ''
                options.Border              (1,:) char = ''
                options.AspectRatio         (1,:) char = ''
            end

            if isempty(parent), parent = uifigure('Name','CSSuiTable'); end
            obj@CSSBase(parent, ...
                'Position', options.Position, ...
                'Enabled',  options.Enabled, ...
                'TempDir',  options.TempDir, ...
                'Style',    options.Style, ...
                'CSS',      options.CSS, ...
                'CSSFile',  options.CSSFile);

            obj.applyCSSOptions(options);
            obj.SelectionChangedFcn = options.SelectionChangedFcn;
            obj.DoubleClickFcn      = options.DoubleClickFcn;
            obj.SelectionType       = options.SelectionType;
            obj.RowStriping         = options.RowStriping;
            obj.Data_               = options.Data;
            obj.ColumnName_         = options.ColumnName;
            obj.ColumnWidth_        = options.ColumnWidth;
            obj.Selection_          = options.Selection;

            obj.endInit();
        end

        % --- Data (patchable via setData command) ------------------------
        function set.Data(obj, val)
            obj.Data_ = val;
            obj.Selection_ = [];   % clear selection on data change
            if ~obj.Updating_ && obj.Loaded_
                obj.pushCmd(struct('cmd','setData', ...
                    'data',      {CSSuiTable.cellToJSArray(val)}, ...
                    'selection', []));
            elseif ~obj.Updating_ && obj.isReady()
                obj.refresh();
            end
        end
        function val = get.Data(obj), val = obj.Data_; end

        % --- ColumnName (structural) -------------------------------------
        function set.ColumnName(obj, val)
            obj.ColumnName_ = val;
            if ~obj.Updating_ && obj.isReady(), obj.refresh(); end
        end
        function val = get.ColumnName(obj), val = obj.ColumnName_; end

        % --- ColumnWidth (structural) ------------------------------------
        function set.ColumnWidth(obj, val)
            obj.ColumnWidth_ = val;
            if ~obj.Updating_ && obj.isReady(), obj.refresh(); end
        end
        function val = get.ColumnWidth(obj), val = obj.ColumnWidth_; end

        % --- Selection (patchable) ----------------------------------------
        function set.Selection(obj, val)
            obj.Selection_ = val;
            if ~obj.Updating_ && obj.Loaded_
                obj.pushCmd(struct('cmd','setSelection','selection',val));
            end
        end
        function val = get.Selection(obj), val = obj.Selection_; end
    end

    % =====================================================================
    methods (Access = protected)

        function html = buildHTML(obj)
            % ---- header row ----
            nCols   = max(size(obj.Data_, 2), numel(obj.ColumnName_));
            if nCols == 0, nCols = 1; end

            hdrHTML = '';
            for c = 1:nCols
                if c <= numel(obj.ColumnName_)
                    label = CSSBase.htmlEscape(char(obj.ColumnName_{c}));
                else
                    label = '';
                end
                wStyle = '';
                if c <= numel(obj.ColumnWidth_) && ~isempty(obj.ColumnWidth_)
                    wStyle = sprintf(' style="width:%dpx;min-width:%dpx;"', ...
                        obj.ColumnWidth_(c), obj.ColumnWidth_(c));
                end
                hdrHTML = [hdrHTML sprintf('<th%s>%s</th>', wStyle, label)]; %#ok<AGROW>
            end

            % ---- body rows ----
            nRows   = size(obj.Data_, 1);
            bodyHTML = '';
            for r = 1:nRows
                selAttr = '';
                if ismember(r, obj.Selection_), selAttr = ' class="tbl-row selected"';
                else,                            selAttr = ' class="tbl-row"';
                end
                rowHTML = sprintf('<tr data-row="%d"%s>', r, selAttr);
                for c = 1:nCols
                    if r <= size(obj.Data_,1) && c <= size(obj.Data_,2)
                        cellVal = obj.Data_{r,c};
                        if isnumeric(cellVal), cellVal = num2str(cellVal); end
                        cellTxt = CSSBase.htmlEscape(char(cellVal));
                    else
                        cellTxt = '';
                    end
                    cellSelClass = '';
                    if strcmp(obj.SelectionType,'cell') && ~isempty(obj.Selection_)
                        if any(obj.Selection_(:,1)==r & obj.Selection_(:,2)==c)
                            cellSelClass = ' class="tbl-cell selected"';
                        end
                    end
                    rowHTML = [rowHTML sprintf('<td data-col="%d"%s>%s</td>', ...
                        c, cellSelClass, cellTxt)]; %#ok<AGROW>
                end
                rowHTML  = [rowHTML '</tr>']; %#ok<AGROW>
                bodyHTML = [bodyHTML rowHTML]; %#ok<AGROW>
            end

            stripingRule = '';
            if obj.RowStriping
                stripingRule = 'tbody tr:nth-child(even){background:rgba(0,0,0,0.035);}';
            end

            css = [ ...
                '#css-root{display:flex;flex-direction:column;' ...
                'padding:var(--outer-padding,0px);}' ...
                '.css-control{' ...
                'flex:1;overflow:auto;' ...
                'background-color:var(--bg-color,#e8e8e8);' ...
                'border-radius:var(--border-radius,8px);' ...
                'box-shadow:var(--inset-shadow,inset 2px 2px 5px #bcbcbc,inset -2px -2px 5px #ffffff);' ...
                'opacity:var(--opacity,1);' ...
                'border:var(--border,none);' ...
                '}' ...
                'table{' ...
                'width:100%;border-collapse:collapse;' ...
                'font-size:var(--font-size,12px);' ...
                'font-family:var(--font-family,inherit);' ...
                'font-weight:var(--font-weight,500);' ...
                'color:var(--color,#5f7080);' ...
                'table-layout:fixed;' ...
                '}' ...
                'thead{position:sticky;top:0;z-index:1;}' ...
                'th{' ...
                'padding:7px 10px;text-align:var(--text-align,left);' ...
                'background:rgba(0,0,0,0.08);' ...
                'font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;' ...
                'border-bottom:1px solid rgba(0,0,0,0.1);' ...
                '}' ...
                'td{' ...
                'padding:5px 10px;' ...
                'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;' ...
                'border-bottom:1px solid rgba(0,0,0,0.04);' ...
                '}' ...
                stripingRule ...
                '.tbl-row{cursor:var(--cursor,default);}' ...
                '.tbl-row.selected td{' ...
                'background:rgba(100,140,200,0.28)!important;' ...
                'color:#2a4a80;' ...
                '}' ...
                '.tbl-cell.selected{' ...
                'background:rgba(100,140,200,0.35)!important;' ...
                'color:#2a4a80;' ...
                '}' ...
                '.tbl-row:hover:not(.selected) td{background:rgba(0,0,0,0.05);}' ...
                '.css-disabled table{opacity:0.5;pointer-events:none;}' ...
            ];

            selTypeJS = ['var _selType="' obj.SelectionType '";'];

            compJS = [ ...
                '<script>' ...
                selTypeJS ...
                'function _getSelection(){' ...
                'var sel=[];' ...
                'if(_selType==="row"){' ...
                'document.querySelectorAll(".tbl-row.selected").forEach(function(r){' ...
                'sel.push(parseInt(r.getAttribute("data-row")));});' ...
                '}else if(_selType==="cell"){' ...
                'document.querySelectorAll(".tbl-cell.selected").forEach(function(td){' ...
                'var r=parseInt(td.parentElement.getAttribute("data-row"));' ...
                'var c=parseInt(td.getAttribute("data-col"));' ...
                'sel.push([r,c]);});' ...
                '}' ...
                'return sel;}' ...
                'var _rowAnchor=null;' ...
                'function _attachRowListeners(tbody){' ...
                'tbody.querySelectorAll(".tbl-row").forEach(function(row){' ...
                'row.addEventListener("click",function(e){' ...
                'if(document.getElementById("css-root").classList.contains("css-disabled"))return;' ...
                'if(_selType==="none")return;' ...
                'if(_selType==="row"){' ...
                'if(e.ctrlKey||e.metaKey){' ...
                'row.classList.toggle("selected");' ...
                '_rowAnchor=row;' ...
                '}else if(e.shiftKey&&_rowAnchor){' ...
                'var rows=Array.from(tbody.querySelectorAll(".tbl-row"));' ...
                'var a=rows.indexOf(_rowAnchor),b=rows.indexOf(row);' ...
                'var lo=Math.min(a,b),hi=Math.max(a,b);' ...
                'rows.forEach(function(r,i){if(i>=lo&&i<=hi)r.classList.add("selected");});' ...
                '}else{' ...
                'tbody.querySelectorAll(".tbl-row").forEach(function(r){r.classList.remove("selected");});' ...
                'row.classList.add("selected");' ...
                '_rowAnchor=row;' ...
                '}' ...
                '}else if(_selType==="cell"){' ...
                'document.querySelectorAll(".tbl-cell.selected").forEach(function(c){c.classList.remove("selected");});' ...
                'var td=e.target.closest("td");if(td){td.classList.add("selected");}' ...
                '}' ...
                'window.sendEvent({event:"change",selection:_getSelection()});' ...
                '});' ...
                'row.addEventListener("dblclick",function(){' ...
                'if(document.getElementById("css-root").classList.contains("css-disabled"))return;' ...
                'window.sendEvent({event:"dblclick",row:parseInt(row.getAttribute("data-row"))});' ...
                '});' ...
                '});' ...
                '}' ...
                'window.componentSetup=function(hc){' ...
                'var tbody=document.querySelector("tbody");' ...
                'if(tbody)_attachRowListeners(tbody);' ...
                '};' ...
                'window.onCommand=function(cmd){' ...
                'if(cmd.cmd==="setData"){' ...
                'var tbody=document.querySelector("tbody");' ...
                'if(!tbody)return;' ...
                'tbody.innerHTML="";' ...
                'cmd.data.forEach(function(row,ri){' ...
                'var tr=document.createElement("tr");' ...
                'tr.className="tbl-row";' ...
                'tr.setAttribute("data-row",ri+1);' ...
                'row.forEach(function(cell,ci){' ...
                'var td=document.createElement("td");' ...
                'td.setAttribute("data-col",ci+1);' ...
                'td.textContent=cell;' ...
                'tr.appendChild(td);' ...
                '});' ...
                'tbody.appendChild(tr);' ...
                '});' ...
                '_attachRowListeners(tbody);' ...
                '}' ...
                'if(cmd.cmd==="setSelection"){' ...
                'var sel=cmd.selection||[];' ...
                'if(_selType==="row"){' ...
                'document.querySelectorAll(".tbl-row").forEach(function(r){' ...
                'var ri=parseInt(r.getAttribute("data-row"));' ...
                'if(sel.indexOf(ri)>=0)r.classList.add("selected");' ...
                'else r.classList.remove("selected");' ...
                '});' ...
                '}' ...
                '}' ...
                '};' ...
                '</script>' ...
            ];

            html = [ ...
                '<!DOCTYPE html><html><head><style>' css '</style></head><body>' ...
                '<div id="css-root">' ...
                '<div class="css-control css-surface">' ...
                '<table><thead><tr>' hdrHTML '</tr></thead>' ...
                '<tbody>' bodyHTML '</tbody></table>' ...
                '</div>' ...
                '</div>' ...
                compJS '</body></html>' ...
            ];
        end

        function onMessage(obj, data)
            switch data.event
                case 'ready'
                    if ~isempty(obj.Selection_)
                        obj.pushCmd(struct('cmd','setSelection', ...
                            'selection', obj.Selection_));
                    end
                case 'change'
                    if obj.Enabled_
                        oldSel = obj.Selection_;
                        raw    = data.selection;
                        if isempty(raw) || (isstruct(raw) && isempty(fieldnames(raw)))
                            newSel = [];
                        elseif strcmp(obj.SelectionType,'row')
                            if isstruct(raw)
                                newSel = cell2mat(struct2cell(raw))';
                            elseif iscell(raw)
                                newSel = cell2mat(raw);
                            else
                                newSel = raw;
                            end
                            newSel = newSel(:)';
                        else
                            % cell mode: list of [r,c] pairs
                            if iscell(raw)
                                newSel = cell2mat(cellfun(@(x)x(:)', raw, 'UniformOutput',false));
                            elseif isstruct(raw)
                                newSel = [];
                                fn = fieldnames(raw);
                                for k = 1:numel(fn)
                                    pair = raw.(fn{k});
                                    if isstruct(pair)
                                        pv = cell2mat(struct2cell(pair))';
                                    else
                                        pv = pair(:)';
                                    end
                                    newSel = [newSel; pv]; %#ok<AGROW>
                                end
                            else
                                newSel = raw;
                            end
                        end
                        obj.Selection_ = newSel;
                        if ~isempty(obj.SelectionChangedFcn)
                            evt = struct('Source', obj, ...
                                'Selection', newSel, ...
                                'PreviousSelection', oldSel);
                            try
                                obj.SelectionChangedFcn(obj, evt);
                            catch ME
                                warning('CSSuiTable:callbackError','%s',ME.message);
                            end
                        end
                    end
                case 'dblclick'
                    if obj.Enabled_ && ~isempty(obj.DoubleClickFcn)
                        evt = struct('Source', obj, 'Row', data.row);
                        try
                            obj.DoubleClickFcn(obj, evt);
                        catch ME
                            warning('CSSuiTable:dblclickError','%s',ME.message);
                        end
                    end
            end
        end

    end

    % =====================================================================
    methods (Static, Access = private)

        function out = cellToJSArray(c)
            %cellToJSArray  Convert N×M cell to cell-of-rows (cell of cell of char).
            % This is the format expected by the JS setData handler.
            if isempty(c)
                out = {};
                return;
            end
            [nr, nc] = size(c);
            out = cell(nr, 1);
            for r = 1:nr
                row = cell(1, nc);
                for col = 1:nc
                    v = c{r,col};
                    if isnumeric(v), v = num2str(v); end
                    row{col} = char(v);
                end
                out{r} = row;
            end
        end

    end

end
