classdef CSSuiTree < CSSBase
    %CSSUITREE  Filterable hierarchical tree backed entirely by HTML/JS.
    %
    %   Purpose:
    %       Native uitree gets sluggish past a few thousand nodes because
    %       each TreeNode is a MATLAB UI primitive. This control renders
    %       the tree as DOM <li> nodes once, then filters by toggling
    %       display:none — interactive on 10k+ nodes.
    %
    %   Usage:
    %       t = CSSuiTree(parent, 'Style','shadow_light');
    %       t.Data = struct('text','Root','data','/path', ...
    %                       'children', { ... nested ... });
    %       t.NodeClickedFcn       = @(s,e) disp(e.NodeData);
    %       t.NodeDoubleClickedFcn = @(s,e) edit(e.NodeData);
    %
    %   Data schema (JSON-encodeable nested struct or cell):
    %       node = struct('text','...', 'data','...', ...
    %                     'isLeaf', tf, 'children', {{ ... }});
    %       'data'     : arbitrary string the JS bridge round-trips back
    %                    via the click event (typically a filesystem path).
    %       'isLeaf'   : optional. Auto-detected from empty children if not set.
    %       'children' : cell array of nested node structs.
    %       Provide a single root node or a cell array of top-level nodes.
    %
    %   Name-Value Pairs:
    %       'Data'                  : struct or cell of structs (default empty)
    %       'ShowSearchBar'         : logical (default true)
    %       'SearchPlaceholder'     : char (default 'Filter…')
    %       'AccentColor'           : char (default '#296ec7')
    %       'ExpandOnFilter'        : logical (default true) — expand all
    %                                 ancestor branches when filter is non-empty
    %       'NodeClickedFcn'        : @(s,e) on single click of a leaf
    %       'NodeDoubleClickedFcn'  : @(s,e) on double-click of a leaf
    %       'SearchSubmittedFcn'    : @(s,e) when query is committed
    %
    %   Event struct fields (NodeClickedFcn / NodeDoubleClickedFcn):
    %       evt.Source   = obj
    %       evt.NodeData = the 'data' field of the clicked node
    %       evt.Text     = the visible label
    %
    %   ∿∿∿  Prerau Laboratory MATLAB Codebase · sleepEEG.org  ∿∿∿

    properties (Access = public)
        ShowSearchBar         = true
        SearchPlaceholder     = 'Filter…'
        AccentColor           = '#296ec7'
        ExpandOnFilter        = true
        NodeClickedFcn        = []
        NodeDoubleClickedFcn  = []
        SearchSubmittedFcn    = []
        MenuActionFcn         = []   % @(src,evt) on context-menu item click;
                                     % evt.Action / .NodeData / .Text
    end

    properties (Dependent)
        Data
        Filter
    end

    properties (Access = protected)
        Data_   = []
        Filter_ = ''
    end

    methods
        function obj = CSSuiTree(parent, options)
            arguments
                parent = []
                options.Position             (1,4) double  = [10 10 320 400]
                options.Enabled              (1,1) logical = true
                options.TempDir              (1,:) char    = tempdir()
                options.Style                              = ''
                options.CSS                  (1,:) char    = ''
                options.CSSFile              (1,:) char    = ''
                options.Data                               = []
                options.ShowSearchBar        (1,1) logical = true
                options.SearchPlaceholder    (1,:) char    = 'Filter…'
                options.AccentColor          (1,:) char    = '#296ec7'
                options.ExpandOnFilter       (1,1) logical = true
                options.NodeClickedFcn                     = []
                options.NodeDoubleClickedFcn               = []
                options.SearchSubmittedFcn                 = []
                options.MenuActionFcn                      = []
                % --- forwarded CSS conveniences --------------------------
                options.Color               (1,:) char = ''
                options.BackgroundColor     (1,:) char = ''
                options.FontSize            (1,:) char = ''
                options.FontFamily          (1,:) char = ''
                options.FontWeight          (1,:) char = ''
                options.BorderRadius        (1,:) char = ''
                options.BoxShadow           (1,:) char = ''
                options.InsetShadow         (1,:) char = ''
                options.Padding             (1,:) char = ''
                options.MinWidth            (1,:) char = ''
                options.MinHeight           (1,:) char = ''
                options.MaxWidth            (1,:) char = ''
                options.MaxHeight           (1,:) char = ''
                options.Width               (1,:) char = ''
                options.Height              (1,:) char = ''
                options.OuterPadding        (1,:) char = ''
                options.Border              (1,:) char = ''
            end

            if isempty(parent), parent = uifigure('Name','CSSuiTree'); end
            obj@CSSBase(parent, ...
                'Position', options.Position, ...
                'Enabled',  options.Enabled, ...
                'TempDir',  options.TempDir, ...
                'Style',    options.Style, ...
                'CSS',      options.CSS, ...
                'CSSFile',  options.CSSFile);

            obj.applyCSSOptions(options);
            obj.ShowSearchBar        = options.ShowSearchBar;
            obj.SearchPlaceholder    = options.SearchPlaceholder;
            obj.AccentColor          = options.AccentColor;
            obj.ExpandOnFilter       = options.ExpandOnFilter;
            obj.NodeClickedFcn       = options.NodeClickedFcn;
            obj.NodeDoubleClickedFcn = options.NodeDoubleClickedFcn;
            obj.SearchSubmittedFcn   = options.SearchSubmittedFcn;
            obj.MenuActionFcn        = options.MenuActionFcn;
            obj.Data_                = options.Data;

            obj.endInit();
        end

        function v = get.Data(obj), v = obj.Data_; end
        function set.Data(obj, val)
            obj.Data_ = val;
            obj.pushDataToJS();
        end

        function v = get.Filter(obj), v = obj.Filter_; end
        function set.Filter(obj, val)
            obj.Filter_ = char(val);
            if ~obj.Updating_ && obj.Loaded_
                obj.pushCmd(struct('cmd','setFilter','value',obj.Filter_));
            end
        end

        function set.SearchPlaceholder(obj, val)
            obj.SearchPlaceholder = val;
            if ~obj.Updating_ && obj.isReady(), obj.refresh(); end
        end
        function set.ShowSearchBar(obj, val)
            obj.ShowSearchBar = val;
            if ~obj.Updating_ && obj.isReady(), obj.refresh(); end
        end
        function set.AccentColor(obj, val)
            obj.AccentColor = val;
            if ~obj.Updating_ && obj.isReady(), obj.refresh(); end
        end

        function expandAll(obj)
            if obj.Loaded_, obj.pushCmd(struct('cmd','expandAll')); end
        end
        function collapseAll(obj)
            if obj.Loaded_, obj.pushCmd(struct('cmd','collapseAll')); end
        end
    end

    methods (Access = protected)

        function pushDataToJS(obj)
            if obj.Updating_, return, end
            % Wrap the cell in an extra {} so struct() doesn't expand a
            % 1×N cell into a struct array — JS expects `tree` to be a
            % JSON array. pushCmd queues until 'ready' fires.
            obj.pushCmd(struct('cmd','setData','tree', {obj.normalizeData()}));
        end

        function tree = normalizeData(obj)
            % Always send a cell array of top-level nodes to JS so the
            % schema is uniform. Single-struct input is wrapped.
            if isempty(obj.Data_)
                tree = {};
            elseif iscell(obj.Data_)
                tree = obj.Data_;
            else
                tree = {obj.Data_};
            end
        end

        function html = buildHTML(obj)
            css = [ ...
                '#css-root{display:flex;flex-direction:column;gap:6px;' ...
                'padding:6px;font-family:var(--font-family,"Segoe UI",system-ui,sans-serif);' ...
                'box-sizing:border-box;height:100%;}' ...
                '.tree-search{position:relative;flex:0 0 auto;height:36px;' ...
                'padding-left:1.1rem;border-radius:var(--border-radius,1.2rem);' ...
                'background:var(--bg-color,#ffffff);' ...
                'box-shadow:var(--inset-shadow,inset 2px 2px 5px #bcbcbc,inset -2px -2px 5px #ffffff);' ...
                'box-sizing:border-box;transition:transform 180ms ease-in-out;}' ...
                '.tree-search.hidden{display:none;}' ...
                '.tree-search input{all:unset;height:100%;width:calc(100% - 2.8rem);' ...
                'color:var(--color,#5f7080);font-size:var(--font-size,12px);font-family:inherit;}' ...
                '.tree-search input::placeholder{color:inherit;opacity:0.45;}' ...
                '.tree-search button{all:unset;position:absolute;right:0;top:0;height:100%;width:2.4rem;' ...
                'border-radius:var(--border-radius,1.2rem);background:var(--accent-color,#296ec7);' ...
                'cursor:pointer;display:flex;align-items:center;justify-content:center;' ...
                'transition:filter 180ms ease-in-out;}' ...
                '.tree-search button:hover{filter:brightness(1.10);}' ...
                '.tree-search .search-icon{position:relative;height:0.7rem;width:0.7rem;' ...
                'border:0.125rem solid white;border-radius:50%;box-sizing:border-box;' ...
                'transform:rotate(-45deg) translateY(-0.05rem);}' ...
                '.tree-search .search-icon::after{content:"";position:absolute;height:0.4rem;' ...
                'width:0.125rem;background:white;left:calc(50% - 0.0625rem);bottom:-0.45rem;}' ...
                '.tree-search:has(input:focus){transform:translateY(-1px);}' ...
                '.tree-wrap{flex:1 1 0;min-height:0;overflow:auto;' ...
                'border-radius:var(--border-radius,8px);background:var(--bg-color,#ffffff);' ...
                'box-shadow:var(--inset-shadow,inset 2px 2px 5px #bcbcbc,inset -2px -2px 5px #ffffff);' ...
                'padding:6px 4px;color:var(--color,#5f7080);font-size:var(--font-size,12px);' ...
                'box-sizing:border-box;}' ...
                'ul.tree,ul.tree ul{list-style:none;margin:0;padding:0;}' ...
                'ul.tree ul{padding-left:18px;position:relative;}' ...
                'ul.tree ul::before{content:"";position:absolute;left:7px;top:0;bottom:0;' ...
                'width:1px;background:rgba(95,112,128,0.18);}' ...
                'li{position:relative;}' ...
                'li.hidden{display:none;}' ...
                '.row{display:flex;align-items:center;gap:4px;padding:2px 6px;' ...
                'border-radius:5px;cursor:pointer;user-select:none;line-height:1.35;' ...
                'transition:background-color 90ms ease;}' ...
                '.row:hover{background:rgba(41,110,199,0.08);}' ...
                'li.leaf.selected > .row{background:rgba(41,110,199,0.22);' ...
                'color:var(--color,#5f7080);font-weight:600;}' ...
                '.chev{width:14px;height:14px;flex-shrink:0;display:inline-flex;' ...
                'align-items:center;justify-content:center;' ...
                'transition:transform 140ms ease;}' ...
                '.chev::before{content:"";display:block;width:0;height:0;' ...
                'border-top:5px solid transparent;border-bottom:5px solid transparent;' ...
                'border-left:7px solid currentColor;opacity:0.75;' ...
                'transform:translateX(1px);}' ...
                'li.dir.expanded > .row > .chev{transform:rotate(90deg);}' ...
                'li.leaf > .row > .chev::before{display:none;}' ...
                'li.leaf > .row::before{content:"";width:5px;height:5px;border-radius:50%;' ...
                'background:rgba(95,112,128,0.35);margin-left:4px;margin-right:5px;' ...
                'flex-shrink:0;}' ...
                'li.leaf > .row > .chev{display:none;}' ...
                'li.dir > .row > .label{font-weight:600;}' ...
                '.label{flex:1 1 auto;min-width:0;overflow:hidden;text-overflow:ellipsis;' ...
                'white-space:nowrap;}' ...
                'ul.tree > li > .row{padding-left:4px;}' ...
                'li.dir > ul{display:none;}' ...
                'li.dir.expanded > ul{display:block;}' ...
                '.tree-empty{color:#9aa3ad;font-style:italic;padding:8px;}' ...
                '.css-disabled #css-root{opacity:0.5;pointer-events:none;}' ...
                '.ctx-menu{position:fixed;z-index:1000;min-width:170px;' ...
                'background:#ffffff;border-radius:8px;padding:4px;' ...
                'box-shadow:0 6px 20px rgba(0,0,30,0.18),0 1px 4px rgba(0,0,0,0.10);' ...
                'border:1px solid rgba(0,0,0,0.08);font-size:var(--font-size,12px);' ...
                'color:var(--color,#5f7080);user-select:none;}' ...
                '.ctx-menu .item{padding:6px 12px;border-radius:5px;cursor:pointer;' ...
                'display:flex;align-items:center;gap:8px;transition:background-color 80ms ease;}' ...
                '.ctx-menu .item:hover{background:rgba(41,110,199,0.12);}' ...
                '.ctx-menu .sep{height:1px;background:rgba(95,112,128,0.18);margin:4px 6px;}' ...
            ];

            compJS = obj.treeJS();

            extraVars = sprintf('<style>:root{--accent-color:%s;}</style>', ...
                CSSBase.attrEscape(obj.AccentColor));

            searchHTML = '';
            if obj.ShowSearchBar
                searchHTML = sprintf(...
                    ['<div class="tree-search css-surface" id="searchbar">' ...
                     '<input id="q" type="text" placeholder="%s">' ...
                     '<button id="go" type="button" aria-label="Search">' ...
                     '<span class="search-icon"></span></button></div>'], ...
                    CSSBase.attrEscape(obj.SearchPlaceholder));
            end

            html = [ ...
                '<!DOCTYPE html><html><head>' extraVars '<style>' css '</style></head><body>' ...
                '<div id="css-root">' searchHTML ...
                '<div class="tree-wrap css-surface"><ul id="tree" class="tree"></ul></div>' ...
                '</div>' compJS '</body></html>'];
        end

        function js = treeJS(obj)
            expandFlag = 'true';
            if ~obj.ExpandOnFilter, expandFlag = 'false'; end

            % All client-side: render once, filter by toggling display:none.
            js = [ ...
                '<script>(function(){' ...
                'var TREE_DATA=[];var EXPAND_ON_FILTER=' expandFlag ';' ...
                'var hc=null;var lastClick={t:0,el:null};' ...
                'function el(tag,cls,txt){var n=document.createElement(tag);' ...
                'if(cls)n.className=cls;if(txt!==undefined)n.textContent=txt;return n;}' ...
                'function buildNode(node){' ...
                ' var li=el("li");' ...
                ' var isLeaf=(node.isLeaf!==undefined)?!!node.isLeaf:!(node.children&&node.children.length);' ...
                ' var hasKids=node.children&&node.children.length;' ...
                ' li.dataset.text=(node.text||"").toLowerCase();' ...
                ' li.dataset.payload=node.data!==undefined?String(node.data):"";' ...
                ' li.dataset.leaf=isLeaf?"1":"0";' ...
                ' if(node.menu&&node.menu.length){' ...
                '  try{li.dataset.menu=JSON.stringify(node.menu);}catch(e){}' ...
                ' }' ...
                ' var row=el("div","row");' ...
                ' var chev=el("span","chev");row.appendChild(chev);' ...
                ' var lab=el("span","label",node.text||"");row.appendChild(lab);' ...
                ' li.appendChild(row);' ...
                ' if(isLeaf){li.classList.add("leaf");}else{li.classList.add("dir");}' ...
                ' if(hasKids){' ...
                '  var ul=el("ul");' ...
                '  for(var i=0;i<node.children.length;i++){ul.appendChild(buildNode(node.children[i]));}' ...
                '  li.appendChild(ul);' ...
                ' }' ...
                ' return li;' ...
                '}' ...
                'function render(tree){' ...
                ' var root=document.getElementById("tree");root.innerHTML="";' ...
                ' if(!tree||!tree.length){' ...
                '  var d=el("div","tree-empty","(no data)");root.parentElement.appendChild(d);return;' ...
                ' }' ...
                ' for(var i=0;i<tree.length;i++){root.appendChild(buildNode(tree[i]));}' ...
                ' attachHandlers(root);' ...
                ' if(tree.length===1){var first=root.firstChild;' ...
                '  if(first&&first.classList.contains("dir"))first.classList.add("expanded");}' ...
                '}' ...
                'function attachHandlers(root){' ...
                ' root.addEventListener("click",function(e){' ...
                '  var row=e.target.closest(".row");if(!row)return;' ...
                '  var li=row.parentElement;if(!li||li.tagName!=="LI")return;' ...
                '  var labelText=(row.querySelector(".label")||{}).textContent||"";' ...
                '  if(li.classList.contains("dir")){' ...
                '   li.classList.toggle("expanded");e.stopPropagation();' ...
                '  }else if(li.classList.contains("leaf")){' ...
                '   var prev=root.querySelector("li.selected");if(prev)prev.classList.remove("selected");' ...
                '   li.classList.add("selected");' ...
                '   var now=Date.now();' ...
                '   var dbl=(lastClick.el===li&&now-lastClick.t<400);' ...
                '   lastClick={t:now,el:li};' ...
                '   var ev=dbl?"nodeDoubleClick":"nodeClick";' ...
                '   window.sendEvent({event:ev,data:li.dataset.payload,text:labelText});' ...
                '   e.stopPropagation();' ...
                '  }' ...
                ' });' ...
                ' root.addEventListener("contextmenu",function(e){' ...
                '  var row=e.target.closest(".row");if(!row)return;' ...
                '  var li=row.parentElement;if(!li||li.tagName!=="LI")return;' ...
                '  var menu=li.dataset.menu;if(!menu)return;' ...
                '  var items;try{items=JSON.parse(menu);}catch(_e){return;}' ...
                '  if(!items||!items.length)return;' ...
                '  e.preventDefault();' ...
                '  var labelText=(row.querySelector(".label")||{}).textContent||"";' ...
                '  showMenu(items,e.clientX,e.clientY,li.dataset.payload,labelText);' ...
                ' });' ...
                '}' ...
                'function dismissMenu(){var m=document.querySelector(".ctx-menu");if(m)m.remove();}' ...
                'function showMenu(items,x,y,payload,labelText){' ...
                ' dismissMenu();' ...
                ' var m=el("div","ctx-menu");' ...
                ' for(var i=0;i<items.length;i++){' ...
                '  var it=items[i];' ...
                '  if(it&&it.sep){m.appendChild(el("div","sep"));continue;}' ...
                '  var d=el("div","item",it.label||it.action||"");' ...
                '  d.dataset.action=it.action||"";' ...
                '  d.addEventListener("click",(function(action){return function(ev){' ...
                '    ev.stopPropagation();dismissMenu();' ...
                '    window.sendEvent({event:"menuAction",action:action,data:payload,text:labelText});' ...
                '  };})(it.action));' ...
                '  m.appendChild(d);' ...
                ' }' ...
                ' document.body.appendChild(m);' ...
                ' var rect=m.getBoundingClientRect();' ...
                ' var maxX=window.innerWidth-rect.width-8;' ...
                ' var maxY=window.innerHeight-rect.height-8;' ...
                ' m.style.left=Math.max(4,Math.min(x,maxX))+"px";' ...
                ' m.style.top=Math.max(4,Math.min(y,maxY))+"px";' ...
                '}' ...
                'document.addEventListener("click",function(e){' ...
                ' if(!e.target.closest(".ctx-menu"))dismissMenu();' ...
                '});' ...
                'document.addEventListener("keydown",function(e){' ...
                ' if(e.key==="Escape")dismissMenu();' ...
                '});' ...
                'window.addEventListener("blur",dismissMenu);' ...
                'function applyFilter(q){' ...
                ' q=(q||"").trim().toLowerCase();' ...
                ' var allLi=document.querySelectorAll("#tree li");' ...
                ' if(!q){' ...
                '  for(var i=0;i<allLi.length;i++)allLi[i].classList.remove("hidden");' ...
                '  return;' ...
                ' }' ...
                ' for(var j=0;j<allLi.length;j++)allLi[j].classList.add("hidden");' ...
                ' for(var k=0;k<allLi.length;k++){' ...
                '  var n=allLi[k];' ...
                '  if(n.dataset.leaf==="1"&&n.dataset.text.indexOf(q)>=0){' ...
                '   var cur=n;' ...
                '   while(cur&&cur.tagName==="LI"){' ...
                '    cur.classList.remove("hidden");' ...
                '    if(EXPAND_ON_FILTER&&cur.classList.contains("dir"))cur.classList.add("expanded");' ...
                '    cur=cur.parentElement&&cur.parentElement.closest("li");' ...
                '   }' ...
                '  }' ...
                ' }' ...
                '}' ...
                'function setQueryUI(v){var i=document.getElementById("q");if(i)i.value=v||"";}' ...
                'function commitQuery(){var i=document.getElementById("q");if(!i)return;' ...
                ' applyFilter(i.value);window.sendEvent({event:"search",value:i.value});}' ...
                'window.componentSetup=function(_hc){hc=_hc;' ...
                ' var i=document.getElementById("q");' ...
                ' if(i){' ...
                '  i.addEventListener("input",function(){applyFilter(i.value);});' ...
                '  i.addEventListener("keydown",function(e){if(e.key==="Enter"){e.preventDefault();commitQuery();}' ...
                '   if(e.key==="Escape"){i.value="";applyFilter("");commitQuery();}});' ...
                '  var b=document.getElementById("go");if(b)b.addEventListener("click",commitQuery);' ...
                ' }' ...
                '};' ...
                'window.onCommand=function(cmd){' ...
                ' if(cmd.cmd==="setData"){TREE_DATA=cmd.tree||[];render(TREE_DATA);}' ...
                ' else if(cmd.cmd==="setFilter"){setQueryUI(cmd.value);applyFilter(cmd.value);}' ...
                ' else if(cmd.cmd==="expandAll"){' ...
                '  var d=document.querySelectorAll("#tree li.dir");for(var i=0;i<d.length;i++)d[i].classList.add("expanded");}' ...
                ' else if(cmd.cmd==="collapseAll"){' ...
                '  var d=document.querySelectorAll("#tree li.dir");for(var i=0;i<d.length;i++)d[i].classList.remove("expanded");}' ...
                '};' ...
                '})();</script>'];
        end

        function onMessage(obj, data)
            switch data.event
                case 'ready'
                    if ~isempty(obj.Data_)
                        obj.pushDataToJS();
                    end
                    if ~isempty(obj.Filter_)
                        obj.pushCmd(struct('cmd','setFilter','value',obj.Filter_));
                    end
                case 'search'
                    obj.Filter_ = data.value;
                    obj.fireCallback(obj.SearchSubmittedFcn, ...
                        struct('Source',obj,'Value',data.value));
                case 'nodeClick'
                    obj.fireCallback(obj.NodeClickedFcn, ...
                        struct('Source',obj,'NodeData',data.data,'Text',data.text));
                case 'nodeDoubleClick'
                    obj.fireCallback(obj.NodeDoubleClickedFcn, ...
                        struct('Source',obj,'NodeData',data.data,'Text',data.text));
                case 'menuAction'
                    obj.fireCallback(obj.MenuActionFcn, ...
                        struct('Source',obj,'Action',data.action, ...
                               'NodeData',data.data,'Text',data.text));
            end
        end

        function fireCallback(obj, fn, evt)
            if isempty(fn), return, end
            try
                if iscell(fn)
                    f = fn{1}; f(obj, evt, fn{2:end});
                else
                    fn(obj, evt);
                end
            catch ME
                warning('CSSuiTree:callback','%s', ME.message);
            end
        end
    end
end
